stages:
  - test
  - deploy
cache:
  paths:
    - node_modules/
run_tests:
  stage: test
  script:
    - npm install --silent -q
    - npm run lint
    - npm test

deploy_project:
  stage: deploy
  script:
    - pm2 deploy ecosystem.config.js ci
  only:
    - dev
