stages:
  - test
  - deploy
cache:
  paths:
    - node_modules/
run_tests:
  stage: test
  script:
    - npm install --silent -q
    - npm run lint
    - npm test

deploy_project:
  stage: deploy
  variables:
    publication_branch_name: "publish-to-heroku"
  script:
    - hostname
    - ssh ubuntu@spina.me
    - cd paging/current
    - pm2 deploy ecosystem.config.js dev
  only:
    - dev
