cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install --silent -q
    - npm run lint


test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - pm2 deploy ecosystem.config.js production
  only:
    - master
